#!/bin/bash

make fclean
make DEBUG=1

for i in {1..10}
do
	./generator $1 | ./lem-in
	sleep 1
done

make re

for i in {1..10}
do
	./generator $1 > tmp
	valgrind --leak-check=full --show-leak-kinds=all ./lem-in < tmp
	sleep 1
done
